// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBph6EW-ZiQOqJtXnc8OvcbvOrWDdWZe0g',
    appId: '1:29065634962:web:1dd41316b0662cc9c7324b',
    messagingSenderId: '29065634962',
    projectId: 'gateguard-br',
    authDomain: 'gateguard-br.firebaseapp.com',
    databaseURL: 'https://gateguard-br-default-rtdb.firebaseio.com',
    storageBucket: 'gateguard-br.appspot.com',
    measurementId: 'G-5FFVQDJ0FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCENvlHVGCdJj-IUYPHjsefDS5N57b6oA0',
    appId: '1:29065634962:android:3416e042960e007dc7324b',
    messagingSenderId: '29065634962',
    projectId: 'gateguard-br',
    databaseURL: 'https://gateguard-br-default-rtdb.firebaseio.com',
    storageBucket: 'gateguard-br.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjRAXVktFf8iZoIjsqOgyRxuKjXfY3O6Q',
    appId: '1:29065634962:ios:457d61f273a8c71dc7324b',
    messagingSenderId: '29065634962',
    projectId: 'gateguard-br',
    databaseURL: 'https://gateguard-br-default-rtdb.firebaseio.com',
    storageBucket: 'gateguard-br.appspot.com',
    iosBundleId: 'com.example.gateguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjRAXVktFf8iZoIjsqOgyRxuKjXfY3O6Q',
    appId: '1:29065634962:ios:457d61f273a8c71dc7324b',
    messagingSenderId: '29065634962',
    projectId: 'gateguard-br',
    databaseURL: 'https://gateguard-br-default-rtdb.firebaseio.com',
    storageBucket: 'gateguard-br.appspot.com',
    iosBundleId: 'com.example.gateguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBph6EW-ZiQOqJtXnc8OvcbvOrWDdWZe0g',
    appId: '1:29065634962:web:7209479361db5033c7324b',
    messagingSenderId: '29065634962',
    projectId: 'gateguard-br',
    authDomain: 'gateguard-br.firebaseapp.com',
    databaseURL: 'https://gateguard-br-default-rtdb.firebaseio.com',
    storageBucket: 'gateguard-br.appspot.com',
    measurementId: 'G-1DFF10SQFB',
  );
}
